### ISSUE TITLE
when the former ttl(upload ttl, not assign ttl) expired, same file uploaded without ttl option, but it can't be downloaded

### ISSUE THREAD

**Issue by chuqingq** [chrislusf/seaweedfs#166]
```
# curl -F file=@start_master.sh http://192.168.23.70:18080/xxxx?ttl=1m
{"name":"start_master.sh","size":645}

// after 1m

# curl -i http://192.168.23.70:18080/xxxx
HTTP/1.1 404 Not Found
Date: Fri, 10 Jul 2015 15:17:47 GMT
Content-Length: 0

# curl -F file=@start_master.sh http://192.168.23.70:18080/xxxx
{"name":"start_master.sh","size":645}

# curl -i http://192.168.23.70:18080/xxxx
HTTP/1.1 404 Not Found
Date: Fri, 10 Jul 2015 15:18:12 GMT
Content-Length: 0
```

If I uploaded another file, it can be downloaded:

```
# curl -F file=@start_volume.sh http://192.168.23.70:18080/xxxx
{"name":"start_volume.sh","size":411}

# curl -i http://192.168.23.70:18080/xxxx
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Disposition: filename="start_volume.sh"
Content-Length: 411
Content-Type: text/x-sh; charset=utf-8
Etag: "63bdc9b5"
Last-Modified: Fri, 10 Jul 2015 15:19:28 GMT
Date: Fri, 10 Jul 2015 15:19:31 GMT

<...>
```

I think if file unchanged but ttl changed, needle should be written to data file:

```golang
func (v *Volume) write(n *Needle) (size uint32, err error) {
	if v.isFileUnchanged(n) {
		size = n.DataSize
		glog.V(4).Infof("needle is unchanged!")
		return
	}
```

**Comment by chrislusf** [comment]
FYI: the fix was wrong, but now I have fixed the fix.

**Comment by chuqingq** [comment]
@chrislusf this problem still exists.

The fix only affects when new ttl is empty, but the new ttl may be not empty. I think the new ttl should affects from uploading time.

**Comment by chrislusf** [comment]
In the examples, are the xxxx different for each request?

**Comment by chuqingq** [comment]
No, xxxx is the same fid in the example.

**Comment by chrislusf** [comment]
ok. I added another fix.

**Comment by chuqingq** [comment]
Still not work.

I think it shouldn't only check for that ttl is empty, but also when ttl is not empty.
If the file is uploaded again, ttl should be written to file, so that it can be downloaded before new ttl expires.

```
$ curl -i http://localhost:9333/dir/assign
HTTP/1.1 200 OK
Content-Type: application/json
Date: Sun, 19 Jul 2015 07:59:44 GMT
Content-Length: 84

{"fid":"2,02e460cd40","url":"127.0.0.1:8080","publicUrl":"127.0.0.1:8080","count":1}
$ curl -F file=@test.log http://localhost:8080/2,02e460cd40?ttl=1m
{"name":"test.log","size":44}
$ curl -i http://localhost:8080/2,02e460cd40
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Disposition: filename="test.log"
Content-Length: 44
Etag: "df20de47"
Last-Modified: Sun, 19 Jul 2015 08:00:00 GMT
Date: Sun, 19 Jul 2015 08:00:57 GMT
Content-Type: text/plain; charset=utf-8

2015/07/15 22:04:18 test.go:16: hello world
<after 1m...>
curl -i http://localhost:8080/2,02e460cd40
I0719 16:01:12  2763 volume_server_handlers_read.go:53] read error: Not Found /2,02e460cd40
HTTP/1.1 404 Not Found
Date: Sun, 19 Jul 2015 08:01:12 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

$ curl -F file=@test.log http://localhost:8080/2,02e460cd40?ttl=1m
{"name":"test.log","size":44}
$ curl -i http://localhost:8080/2,02e460cd40
I0719 16:01:22  2763 volume_server_handlers_read.go:53] read error: Not Found /2,02e460cd40
HTTP/1.1 404 Not Found
Date: Sun, 19 Jul 2015 08:01:22 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

```

**Comment by chuqingq** [comment]
@chrislusf

**Comment by chrislusf** [comment]
You should request a ttl volume instead of a common volume.

$ curl -i http://localhost:9333/dir/assign?ttl=1m
