### ISSUE TITLE
Validate filesystem against pjdfstest

### ISSUE THREAD

**Issue by nickb937** [chrislusf/seaweedfs#2569]
**Describe the bug**

SeaweedFS version 2.8.3

```
/usr/local/bin/etcd --name s2 --data-dir /home/etcd --listen-client-urls http://192.168.1.253:22379 --advertise-client-urls http://192.168.1.253:22379 --listen-peer-urls http://192.168.1.253:22380 --initial-advertise-peer-urls http://192.168.1.253:22380 --initial-cluster s1=http://192.168.1.254:2380,s2=http://192.168.1.253:22380,s3=http://192.168.1.3:32380 --initial-cluster-token tkn --initial-cluster-state new

/usr/local/bin/weed master -mdir=/home/weedfs/master -volumePreallocate -volumeSizeLimitMB=32768 -ip 192.168.1.253 -peers 192.168.1.254:9333,192.168.1.253:9333,192.168.1.3:9333

/usr/local/bin/weed volume -dir=/lizardfs/14tb.4cec/seaweedfs -mserver=192.168.1.253:9333,192.168.1.254:9333,192.168.1.3:9333 -port=8088 -port.grpc=18088 -ip=192.168.1.10 -max=32768 -index=leveldb -dataCenter=shed

weed mount -filer=localhost:8888 -dir=/mnt/weed
```

I came across https://github.com/chrislusf/seaweedfs/issues/1308 (sqlite corruption) whilst trying to start Lidarr (https://github.com/Lidarr/Lidarr) with the config on SeaweedFS -- `lidarr -config=/mnt/weed/data` is sufficient to fail on application start

So I thought it might be an idea to run the filesystem test suite - https://github.com/pjd/pjdfstest

```
prove -rv /home/nickb/src/pjdfstest/tests


Test Summary Report
-------------------
/home/nickb/src/pjdfstest/tests/chmod/00.t          (Wstat: 0 Tests: 119 Failed: 5)
  Failed tests:  68, 72, 76, 80, 84
/home/nickb/src/pjdfstest/tests/chmod/11.t          (Wstat: 0 Tests: 109 Failed: 24)
  Failed tests:  4, 7, 12, 15, 20, 23, 28, 31, 36, 39, 44
                47, 53, 56, 64, 66, 74, 76, 84, 86, 94
                96, 104, 106
/home/nickb/src/pjdfstest/tests/chmod/12.t          (Wstat: 0 Tests: 14 Failed: 6)
  Failed tests:  3-4, 7-8, 11-12
/home/nickb/src/pjdfstest/tests/chown/00.t          (Wstat: 0 Tests: 1323 Failed: 32)
  Failed tests:  970, 973, 977, 980, 986, 989, 994, 997
                1001, 1004, 1010, 1013, 1018, 1021, 1025
                1028, 1034, 1037, 1042, 1045, 1049, 1052
                1058, 1061, 1066, 1069, 1073, 1076, 1082
                1085, 1090, 1093
  TODO passed:   1112, 1116, 1122, 1127, 1131, 1137, 1142
                1146, 1152, 1157, 1161, 1167, 1172, 1176
                1182, 1187
/home/nickb/src/pjdfstest/tests/link/00.t           (Wstat: 0 Tests: 202 Failed: 44)
  Failed tests:  8, 13, 15, 18-19, 22, 34, 39, 41, 44-45
                48, 60, 65, 67, 70-71, 74, 86, 91, 93, 96-97
                100, 112, 117, 119, 122-123, 126, 135-136
                141-143, 148-150, 155-157, 162-164
/home/nickb/src/pjdfstest/tests/link/03.t           (Wstat: 0 Tests: 13 Failed: 1)
  Failed test:  11
/home/nickb/src/pjdfstest/tests/mkdir/00.t          (Wstat: 0 Tests: 36 Failed: 2)
  Failed tests:  33-34
/home/nickb/src/pjdfstest/tests/mkfifo/00.t         (Wstat: 0 Tests: 36 Failed: 4)
  Failed tests:  30, 32-34
/home/nickb/src/pjdfstest/tests/mknod/00.t          (Wstat: 0 Tests: 36 Failed: 4)
  Failed tests:  30, 32-34
/home/nickb/src/pjdfstest/tests/mknod/11.t          (Wstat: 0 Tests: 28 Failed: 10)
  Failed tests:  4, 9, 11-13, 17, 22, 24-26
/home/nickb/src/pjdfstest/tests/open/00.t           (Wstat: 0 Tests: 47 Failed: 4)
  Failed tests:  30, 32-34
/home/nickb/src/pjdfstest/tests/open/02.t           (Wstat: 0 Tests: 4 Failed: 1)
  Failed test:  2
/home/nickb/src/pjdfstest/tests/open/03.t           (Wstat: 0 Tests: 4 Failed: 1)
  Failed test:  2
/home/nickb/src/pjdfstest/tests/rename/00.t         (Wstat: 0 Tests: 122 Failed: 17)
  Failed tests:  7, 10, 14, 22, 25, 29, 37, 40, 44, 52, 55
                59, 67, 70, 74, 81, 91
/home/nickb/src/pjdfstest/tests/rename/09.t         (Wstat: 0 Tests: 2353 Failed: 592)
  Failed tests:  12, 20, 22, 28, 30, 36, 38, 44, 46, 52
                54, 60, 62, 70, 78, 80, 86, 88, 94, 96
                102, 104, 110, 112, 118, 120, 128, 136
                138, 144, 146, 152, 154, 160, 162, 168
                170, 176, 178, 186, 194, 196, 202, 204
                210, 212, 218, 220, 226, 228, 234, 236
                244, 252, 254, 260, 262, 268, 270, 276
                278, 284, 286, 292, 294, 300-302, 304-305
                310-311, 316-317, 322-323, 328-329, 334-335
                338, 342-344, 346-347, 352-353, 358-359
                364-365, 370-371, 376-377, 380, 386, 394
                396, 402, 404, 410, 412, 418, 420, 426
                428, 434, 436, 444, 452, 454, 460, 462
                468, 470, 476, 478, 484, 486, 492, 494
                502, 510, 512, 518, 520, 526, 528, 534
                536, 542, 544, 550, 552, 560, 568, 570
                576, 578, 584, 586, 592, 594, 600, 602
                608, 610, 618, 626, 628, 634, 636, 642
                644, 650, 652, 658, 660, 666, 668, 674-676
                678-679, 684-685, 690-691, 696-697, 702-703
                708-709, 712, 716-718, 720-721, 726-727
                732-733, 738-739, 744-745, 750-751, 754
                760, 768, 770, 776, 778, 784, 786, 792
                794, 800, 802, 808, 810, 818, 826, 828
                834, 836, 842, 844, 850, 852, 858, 860
                866, 868, 876, 884, 886, 892, 894, 900
                902, 908, 910, 916, 918, 924, 926, 934
                942, 944, 950, 952, 958, 960, 966, 968
                974, 976, 982, 984, 992, 1000, 1002, 1008
                1010, 1016, 1018, 1024, 1026, 1032, 1034
                1040, 1042, 1048-1050, 1052-1053, 1058-1059
                1064-1065, 1070-1071, 1076-1077, 1082-1083
                1086, 1090-1092, 1094-1095, 1100-1101, 1106-1107
                1112-1113, 1118-1119, 1124-1125, 1128, 1134
                1142, 1144, 1150, 1152, 1158, 1160, 1166
                1168, 1174, 1176, 1182, 1184, 1192, 1200
                1202, 1208, 1210, 1216, 1218, 1224, 1226
                1232, 1234, 1240, 1242, 1250, 1258, 1260
                1266, 1268, 1274, 1276, 1282, 1284, 1290
                1292, 1298, 1300, 1308, 1316, 1318, 1324
                1326, 1332, 1334, 1340, 1342, 1348, 1350
                1356, 1358, 1366, 1374, 1376, 1382, 1384
                1390, 1392, 1398, 1400, 1406, 1408, 1414
                1416, 1422-1424, 1426-1427, 1432-1433, 1438-1439
                1444-1445, 1450-1451, 1456-1457, 1460, 1464-1466
                1468-1469, 1474-1475, 1480-1481, 1486-1487
                1492-1493, 1498-1499, 1502, 1508, 1516
                1518, 1524, 1526, 1532, 1534, 1540, 1542
                1548, 1550, 1556, 1558, 1566, 1574, 1576
                1582, 1584, 1590, 1592, 1598, 1600, 1606
                1608, 1614, 1616, 1624, 1632, 1634, 1640
                1642, 1648, 1650, 1656, 1658, 1664, 1666
                1672, 1674, 1682, 1690, 1692, 1698, 1700
                1706, 1708, 1714, 1716, 1722, 1724, 1730
                1732, 1740, 1748, 1750, 1756, 1758, 1764
                1766, 1772, 1774, 1780, 1782, 1788, 1790
                1796-1798, 1800-1801, 1806-1807, 1812-1813
                1818-1819, 1824-1825, 1830-1831, 1834, 1838-1840
                1842-1843, 1848-1849, 1854-1855, 1860-1861
                1866-1867, 1872-1873, 1876, 1882, 1890
                1892, 1898, 1900, 1906, 1908, 1914, 1916
                1922, 1924, 1930, 1932, 1940, 1948, 1950
                1956, 1958, 1964, 1966, 1972, 1974, 1980
                1982, 1988, 1990, 1998, 2006, 2008, 2014
                2016, 2022, 2024, 2030, 2032, 2038, 2040
                2046, 2048, 2056, 2064, 2066, 2072, 2074
                2080, 2082, 2088, 2090, 2096, 2098, 2104
                2106, 2114, 2122, 2124, 2130, 2132, 2138
                2140, 2146, 2148, 2154, 2156, 2162, 2164
                2170-2172, 2174-2175, 2180-2181, 2186-2187
                2192-2193, 2198-2199, 2204-2205, 2208, 2212-2214
                2216-2217, 2222-2223, 2228-2229, 2234-2235
                2240-2241, 2246-2247, 2250, 2256, 2261
                2271, 2281, 2291, 2301, 2308, 2313, 2320
                2325
/home/nickb/src/pjdfstest/tests/rename/10.t         (Wstat: 0 Tests: 2099 Failed: 541)
  Failed tests:  13, 15, 21, 23, 29, 31, 37, 39, 45, 47
                53, 55, 65, 67, 73, 75, 81, 83, 89, 91
                97, 99, 105, 107, 117, 119, 125, 127, 133
                135, 141, 143, 149, 151, 157, 159, 169
                171, 177, 179, 185, 187, 193, 195, 201
                203, 209, 211, 221, 223, 229, 231, 237
                239, 245, 247, 253, 255, 261, 263, 271-273
                277-278, 283-284, 289-290, 295-296, 301-302
                305, 311-313, 317-318, 323-324, 329-330
                335-336, 341-342, 345, 353, 355, 361, 363
                369, 371, 377, 379, 385, 387, 393, 395
                405, 407, 413, 415, 421, 423, 429, 431
                437, 439, 445, 447, 457, 459, 465, 467
                473, 475, 481, 483, 489, 491, 497, 499
                509, 511, 517, 519, 525, 527, 533, 535
                541, 543, 549, 551, 561, 563, 569, 571
                577, 579, 585, 587, 593, 595, 601, 603
                611-613, 617-618, 623-624, 629-630, 635-636
                641-642, 645, 651-653, 657-658, 663-664
                669-670, 675-676, 681-682, 685, 693, 695
                701, 703, 709, 711, 717, 719, 725, 727
                733, 735, 745, 747, 753, 755, 761, 763
                769, 771, 777, 779, 785, 787, 797, 799
                805, 807, 813, 815, 821, 823, 829, 831
                837, 839, 849, 851, 857, 859, 865, 867
                873, 875, 881, 883, 889, 891, 901, 903
                909, 911, 917, 919, 925, 927, 933, 935
                941, 943, 951-953, 957-958, 963-964, 969-970
                975-976, 981-982, 985, 991-993, 997-998
                1003-1004, 1009-1010, 1015-1016, 1021-1022
                1025, 1033, 1035, 1041, 1043, 1049, 1051
                1057, 1059, 1065, 1067, 1073, 1075, 1085
                1087, 1093, 1095, 1101, 1103, 1109, 1111
                1117, 1119, 1125, 1127, 1137, 1139, 1145
                1147, 1153, 1155, 1161, 1163, 1169, 1171
                1177, 1179, 1189, 1191, 1197, 1199, 1205
                1207, 1213, 1215, 1221, 1223, 1229, 1231
                1241, 1243, 1249, 1251, 1257, 1259, 1265
                1267, 1273, 1275, 1281, 1283, 1291-1293
                1297-1298, 1303-1304, 1309-1310, 1315-1316
                1321-1322, 1325, 1331-1333, 1337-1338, 1343-1344
                1349-1350, 1355-1356, 1361-1362, 1365, 1373
                1375, 1381, 1383, 1389, 1391, 1397, 1399
                1405, 1407, 1413, 1415, 1425, 1427, 1433
                1435, 1441, 1443, 1449, 1451, 1457, 1459
                1465, 1467, 1477, 1479, 1485, 1487, 1493
                1495, 1501, 1503, 1509, 1511, 1517, 1519
                1529, 1531, 1537, 1539, 1545, 1547, 1553
                1555, 1561, 1563, 1569, 1571, 1581, 1583
                1589, 1591, 1597, 1599, 1605, 1607, 1613
                1615, 1621, 1623, 1631-1633, 1637-1638
                1643-1644, 1649-1650, 1655-1656, 1661-1662
                1665, 1671-1673, 1677-1678, 1683-1684, 1689-1690
                1695-1696, 1701-1702, 1705, 1713, 1715
                1721, 1723, 1729, 1731, 1737, 1739, 1745
                1747, 1753, 1755, 1765, 1767, 1773, 1775
                1781, 1783, 1789, 1791, 1797, 1799, 1805
                1807, 1817, 1819, 1825, 1827, 1833, 1835
                1841, 1843, 1849, 1851, 1857, 1859, 1869
                1871, 1877, 1879, 1885, 1887, 1893, 1895
                1901, 1903, 1909, 1911, 1921, 1923, 1929
                1931, 1937, 1939, 1945, 1947, 1953, 1955
                1961, 1963, 1971-1973, 1977-1978, 1983-1984
                1989-1990, 1995-1996, 2001-2002, 2005, 2011-2013
                2017-2018, 2023-2024, 2029-2030, 2035-2036
                2041-2042, 2045, 2051, 2058, 2065, 2072
                2079, 2084-2087, 2092-2095
/home/nickb/src/pjdfstest/tests/rename/20.t         (Wstat: 0 Tests: 25 Failed: 8)
  Failed tests:  4, 7, 10, 13, 16, 19, 22, 25
/home/nickb/src/pjdfstest/tests/rename/21.t         (Wstat: 0 Tests: 16 Failed: 4)
  Failed tests:  5, 12-14
/home/nickb/src/pjdfstest/tests/rename/23.t         (Wstat: 0 Tests: 42 Failed: 10)
  Failed tests:  6-7, 14-15, 22-23, 30-31, 38-39
/home/nickb/src/pjdfstest/tests/rmdir/00.t          (Wstat: 0 Tests: 10 Failed: 2)
  Failed tests:  8-9
/home/nickb/src/pjdfstest/tests/rmdir/06.t          (Wstat: 0 Tests: 23 Failed: 21)
  Failed tests:  3-23
/home/nickb/src/pjdfstest/tests/rmdir/11.t          (Wstat: 0 Tests: 47 Failed: 6)
  Failed tests:  36-38, 43-45
/home/nickb/src/pjdfstest/tests/symlink/00.t        (Wstat: 0 Tests: 14 Failed: 2)
  Failed tests:  11-12
/home/nickb/src/pjdfstest/tests/unlink/00.t         (Wstat: 0 Tests: 112 Failed: 18)
  Failed tests:  29, 34, 39, 44, 49, 74-75, 80-81, 86-87
                92-93, 98-99, 104-105, 110
/home/nickb/src/pjdfstest/tests/unlink/11.t         (Wstat: 0 Tests: 270 Failed: 36)
  Failed tests:  39-41, 46-48, 83-85, 90-92, 127-129, 134-136
                171-173, 178-180, 215-217, 222-224, 259-261
                266-268
/home/nickb/src/pjdfstest/tests/unlink/14.t         (Wstat: 0 Tests: 7 Failed: 1)
  Failed test:  4
/home/nickb/src/pjdfstest/tests/utimensat/00.t      (Wstat: 0 Tests: 32 Failed: 6)
  Failed tests:  4, 9, 14, 19, 24, 29
/home/nickb/src/pjdfstest/tests/utimensat/01.t      (Wstat: 0 Tests: 7 Failed: 1)
  Failed test:  5
/home/nickb/src/pjdfstest/tests/utimensat/02.t      (Wstat: 0 Tests: 10 Failed: 2)
  Failed tests:  4, 7
/home/nickb/src/pjdfstest/tests/utimensat/04.t      (Wstat: 0 Tests: 10 Failed: 2)
  Failed tests:  4, 7
/home/nickb/src/pjdfstest/tests/utimensat/05.t      (Wstat: 0 Tests: 16 Failed: 3)
  Failed tests:  5, 7, 10
/home/nickb/src/pjdfstest/tests/utimensat/08.t      (Wstat: 0 Tests: 9 Failed: 1)
  Failed test:  5
/home/nickb/src/pjdfstest/tests/utimensat/09.t      (Wstat: 0 Tests: 7 Failed: 1)
  Failed test:  4
Files=236, Tests=8818, 294 wallclock secs ( 3.48 usr  0.52 sys + 56.33 cusr 26.88 csys = 87.21 CPU)
Result: FAIL
```

**Expected behavior**

All tests should pass

**Comment by tjohnston-cd** [comment]
See also #1588 - also of interest to me (and probably lots of others).

Need to come back to this and see how we can help in sorting it out...

**Comment by chrislusf** [comment]
Need a way to make it a little bit easier to track the progress. 

Creating some docker compose file similar to S3 test suite would be nice.

**Comment by tjohnston-cd** [comment]
So you want a CI step that runs a container with pjdfstest preinstalled, runs the test suite against a simple setup (e.g. same masters/volumes/etc as the other test steps).

There are past PRs with CI changes we can use as a reference. 

Once we have this, what's next? Have to go one-by-one and make changes so tests pass.. Hopefully it will mostly be filer/mount changes?

**Comment by chrislusf** [comment]
Yes. We can track the improvements over time and avoid regressions. The POSIX is complicated and would not be 100% in the end.

**Comment by chrislusf** [comment]
I added a few fixes for POSIX, following the pjdfstest and skipping some non-essential ones. (FIFO, char devices, etc).

Seems one strange bug is fixed now. https://github.com/chrislusf/seaweedfs/issues/2561

@nickb937 Could you please help to run the lidarr again and see whether it helps? 
The POSIX work is still in progress. I just want to see whether current fixes are good enough for lidarr.

**Comment by nickb937** [comment]
I took a snapshot from https://github.com/chrislusf/seaweedfs/commit/fe5b9e39cc5a3526a0fdadf8b518b67b02d5451b and ran the system using it.  The end result is that lidarr now starts, so the situation is definitely better than before.

The application operates and still reports disk IO errors, which I suspect is concurrency related (multiple threads accessing the DB), but I will have to try to produce a testcase for it.

**Comment by nickb937** [comment]
dt is a filesystem exerciser that you may want to try: https://github.com/RobinTMiller/dt

Tests pass:
./linux.d/dt of=/mnt/weed/x workload=longevity_file_system runtime=5 limit=4120k  disable=stats enable=job_stats

Anything larger than a transfer limit of 4120k fails:

./linux.d/dt of=/mnt/weed/x workload=longevity_file_system runtime=5 limit=5000k  disable=stats enable=job_stats

**Comment by chrislusf** [comment]
@nickb937 thanks for testing and the link. "dt" has some good tests on IO patterns.

**Comment by chrislusf** [comment]
Fixed some concurrency issues found in "dt".

@nickb937 maybe try it out again?

**Comment by nickb937** [comment]
Generally the issue still remains.  I will aim to produce a test case and open an issue if I am successful in doing so

**Comment by nickb937** [comment]
Actually, I'm pleased to report that Lidarr is correctly starting up, without the sqlite corruption now.
Looks like I'd missed upgrading a component when I re-tested, earlier

**Comment by chrislusf** [comment]
Thanks for reporting this! Best news after 3 days of heavy debugging! :)
