### ISSUE TITLE
seaweedfs should support 0-size file uploading and downloading

### ISSUE THREAD

**Issue by chuqingq** [chrislusf/seaweedfs#409]
Now, 0-size text file can be uploaded and download successfully.
But, 0-size jpg file(or other not isGzippable()) can not be uploaded, report `{"name":"empty.doc","error":"Failed to write to local disk"}`.

I suggest seaweedfs should support 0-size all format file unploading and downloading, or return `400 bad request` when being uploaded.

0-size text file uploaded  successfully:
```
# curl -F file=@empty.txt 192.168.4.18:28083/45,6c8916e496119e -v
* Hostname was NOT found in DNS cache
*   Trying 192.168.4.18...
* Connected to 192.168.4.18 (192.168.4.18) port 28083 (#0)
> POST /45,6c8916e496119e HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 192.168.4.18:28083
> Accept: */*
> Content-Length: 187
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------bcba47b57757d366
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 201 Created
< Content-Type: application/json
< Date: Tue, 06 Dec 2016 07:34:49 GMT
< Content-Length: 30
< 
* Connection #0 to host 192.168.4.18 left intact
{"name":"empty.txt","size":23}
```

0-size doc file uploaded unsuccessfully:
```
# curl -F file=@empty.doc 192.168.4.18:28083/45,6c8916e496119e -v
* Hostname was NOT found in DNS cache
*   Trying 192.168.4.18...
* Connected to 192.168.4.18 (192.168.4.18) port 28083 (#0)
> POST /45,6c8916e496119e HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 192.168.4.18:28083
> Accept: */*
> Content-Length: 201
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------8228c550c48374e5
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Tue, 06 Dec 2016 07:30:34 GMT
< Content-Length: 60
* HTTP error before end of send, stop sending
< 
* Closing connection 0
{"name":"empty.doc","error":"Failed to write to local disk"}
```

**Comment by chrislusf** [comment]
fixed.

**Comment by frol** [comment]
I still see this error in the latest 0.76 release. Should this be reopened?

**Comment by chrislusf** [comment]
The fix was https://github.com/chrislusf/seaweedfs/commit/3cb00710252ac004569eeeb73adace5024e9a2cc

The error now could be different.

**Comment by frol** [comment]
I use the prebuilt Docker containers if that matters, and here is what I see:

```
$ curl -X POST http://seaweedfs-master:9333/dir/assign
{"fid":"5,15081ac9d9","url":"172.29.0.4:8888","publicUrl":"172.29.0.4:8888","count":1}

$ curl -X PUT -F file=@/opt/www/tests/q http://172.29.0.4:8888/5,15081ac9d9
{"name":"q","error":"Failed to write to local disk"}

$ curl -i -X PUT -F file=@/opt/www/tests/q http://172.29.0.4:8888/5,15081ac9d9
HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Etag: "00000000"
Date: Wed, 14 Jun 2017 12:41:11 GMT
Content-Length: 52

{"name":"q","error":"Failed to write to local disk"}
```

If I put any content into the `q` file, it uploads just fine.
